# Generated by Django 5.1.4 on 2025-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_judge_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='compnay',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='judge',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
