# Generated by Django 5.1.4 on 2025-02-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_capacity_event_created_at_event_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='span',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
