# Generated by Django 5.1.4 on 2025-02-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reg_no',
            field=models.IntegerField(),
        ),
    ]
